version: '3.9'


networks:
  extsvcs:
    external: true

services:
  newlook:
    container_name: newlook
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4249:4242"
    networks:
      - extsvcs
    restart: always